"""W2 — end-to-end gate test for HarnessExampleStore.record_run.

Uses the real HarnessOrchestrator to produce a low-confidence report on
a 45-byte identity-passthrough Lua body. Asserts that record_run does
NOT write any files under output/generated_lua/, returns
accepted=False, lua_path=None, and rejection_reason indicates the
expected gate hit.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from components.testing_harness.harness_orchestrator import HarnessOrchestrator
from components.web_ui.example_store import HarnessExampleStore


_IDENTITY_PASSTHROUGH = "function processEvent(event) return event end"


def test_record_run_rejects_identity_passthrough_with_real_harness(tmp_path: Path):
    """Real harness on a 45-byte body produces a low score; gate rejects."""
    parser_name = "okta_logs-latest"
    parser_config = {
        "parser_name": parser_name,
        "config": {"parser_name": parser_name},
        "raw_examples": ['{"eventType":"user.session.start","actor":{"alternateId":"alice@example.com"}}'],
    }

    orchestrator = HarnessOrchestrator()
    report = orchestrator.run_all_checks(
        lua_code=_IDENTITY_PASSTHROUGH,
        parser_config=parser_config,
        ocsf_version="1.3.0",
    )

    # Sanity check: the real harness must produce a low confidence_score
    # for a 45-byte identity-passthrough body. If this assertion ever
    # fails, the harness has regressed and the gate test is meaningless.
    assert report["confidence_score"] < 70, (
        f"Real harness should score identity passthrough below 70, "
        f"got {report['confidence_score']}"
    )

    store = HarnessExampleStore(repo_root=tmp_path)
    run_result = store.record_run(
        parser_name=parser_name,
        lua_code=_IDENTITY_PASSTHROUGH,
        harness_report=report,
        sample_provenance={"source": "user_raw_examples"},
    )

    # Acceptance gate fires.
    assert run_result["accepted"] is False
    assert run_result["lua_path"] is None
    assert run_result["report_path"] is None
    assert run_result["run_id"] is None
    # Either too_short (45 < 100) or low_confidence_score is acceptable;
    # the size gate runs first and the body is 45 bytes, so we expect
    # too_short. (low_confidence_score path is exercised separately via
    # tests/test_lua_acceptance.py.)
    assert run_result["rejection_reason"] in ("too_short", "low_confidence_score")

    # Verify that no Lua file or report file was written under the
    # temp output/generated_lua/ root.
    generated_lua_root = tmp_path / "output" / "generated_lua"
    harness_reports_root = tmp_path / "output" / "harness_reports"
    if generated_lua_root.exists():
        assert not list(generated_lua_root.rglob("*.lua")), (
            "No .lua file should have been written"
        )
    if harness_reports_root.exists():
        assert not list(harness_reports_root.rglob("*.json")), (
            "No .json report should have been written"
        )


def test_record_run_rejects_low_confidence_with_synthetic_report(tmp_path: Path):
    """A wrapped-but-low-score body is rejected with low_confidence_score."""
    wrapped_lua = (
        "-- generated by tests; passes length but fails the score gate\n"
        "function processEvent(event)\n"
        "  local out = {}\n"
        "  out.class_uid = 4001\n"
        "  out.activity_id = 1\n"
        "  out.metadata = {product = {vendor_name = 'tests'}}\n"
        "  return out\n"
        "end\n"
    )
    parser_name = "okta_logs-latest"
    store = HarnessExampleStore(repo_root=tmp_path)
    run_result = store.record_run(
        parser_name=parser_name,
        lua_code=wrapped_lua,
        harness_report={"confidence_score": 50},
        sample_provenance={"source": "user_raw_examples"},
    )

    assert run_result["accepted"] is False
    assert run_result["lua_path"] is None
    assert run_result["rejection_reason"] == "low_confidence_score"

    generated_lua_root = tmp_path / "output" / "generated_lua"
    if generated_lua_root.exists():
        assert not list(generated_lua_root.rglob("*.lua"))


def test_record_run_accepts_passing_lua(tmp_path: Path):
    wrapped_lua = (
        "-- generated by tests; passes the gate\n"
        "function processEvent(event)\n"
        "  local out = {}\n"
        "  out.class_uid = 4001\n"
        "  out.activity_id = 1\n"
        "  out.metadata = {product = {vendor_name = 'tests'}}\n"
        "  return out\n"
        "end\n"
    )
    parser_name = "okta_logs-latest"
    store = HarnessExampleStore(repo_root=tmp_path)
    run_result = store.record_run(
        parser_name=parser_name,
        lua_code=wrapped_lua,
        harness_report={"confidence_score": 80},
        sample_provenance={"source": "user_raw_examples"},
    )

    assert run_result["accepted"] is True
    assert run_result["rejection_reason"] is None
    assert run_result["run_id"]
    assert Path(run_result["lua_path"]).exists()
    assert Path(run_result["report_path"]).exists()
