"""W2 — unit tests for components.web_ui.lua_acceptance.is_acceptable_lua."""

from __future__ import annotations

from components.web_ui.lua_acceptance import is_acceptable_lua


_IDENTITY_PASSTHROUGH = "function processEvent(event) return event end"

_WRAPPED_LUA = (
    "-- generated by tests; passes the helper length+identity gate\n"
    "function processEvent(event)\n"
    "  local out = {}\n"
    "  out.class_uid = 4001\n"
    "  out.activity_id = 1\n"
    "  out.metadata = {product = {vendor_name = 'tests'}}\n"
    "  if event and event.type then out.activity_name = event.type end\n"
    "  return out\n"
    "end\n"
)


def test_identity_passthrough_rejected_even_with_high_score():
    """45-byte identity passthrough is rejected even with confidence_score=100."""
    assert len(_IDENTITY_PASSTHROUGH) == 45
    accepted, reason = is_acceptable_lua(
        _IDENTITY_PASSTHROUGH, harness_report={"confidence_score": 100}
    )
    assert accepted is False
    # The size gate fires first (45 < default min_length=100), which is
    # the dominant rejection shape for the C2 contamination.
    assert reason == "too_short"


def test_identity_passthrough_rejected_with_lowered_min_length():
    """When the size gate is lowered, identity passthrough is still rejected
    via the explicit identity-passthrough check."""
    accepted, reason = is_acceptable_lua(
        _IDENTITY_PASSTHROUGH,
        harness_report={"confidence_score": 100},
        min_length=10,
    )
    assert accepted is False
    assert reason == "identity_passthrough"


def test_low_confidence_score_rejected():
    """200-byte wrapped Lua with confidence_score=50 is rejected."""
    assert len(_WRAPPED_LUA) >= 100
    accepted, reason = is_acceptable_lua(
        _WRAPPED_LUA, harness_report={"confidence_score": 50}
    )
    assert accepted is False
    assert reason == "low_confidence_score"


def test_high_confidence_score_accepted():
    """Wrapped Lua with confidence_score=80 is accepted."""
    accepted, reason = is_acceptable_lua(
        _WRAPPED_LUA, harness_report={"confidence_score": 80}
    )
    assert accepted is True
    assert reason is None


def test_harness_report_none_accepted_when_size_and_identity_pass():
    """harness_report=None skips the score gate; size + identity still apply."""
    accepted, reason = is_acceptable_lua(_WRAPPED_LUA, harness_report=None)
    assert accepted is True
    assert reason is None


def test_empty_lua_rejected():
    accepted, reason = is_acceptable_lua("", harness_report=None)
    assert accepted is False
    assert reason == "too_short"


def test_none_lua_rejected():
    # The helper is documented as accepting str; defensively handle None.
    accepted, reason = is_acceptable_lua(None, harness_report=None)  # type: ignore[arg-type]
    assert accepted is False
    assert reason == "too_short"


def test_whitespace_only_lua_rejected():
    accepted, reason = is_acceptable_lua("   \n\t   \n", harness_report=None)
    assert accepted is False
    assert reason == "too_short"


def test_score_exactly_at_threshold_accepted():
    """confidence_score == min_confidence is accepted (>=, not >)."""
    accepted, reason = is_acceptable_lua(
        _WRAPPED_LUA, harness_report={"confidence_score": 70}
    )
    assert accepted is True
    assert reason is None


def test_missing_confidence_score_treated_as_zero():
    """A harness_report dict without confidence_score is treated as 0."""
    accepted, reason = is_acceptable_lua(
        _WRAPPED_LUA, harness_report={"some_other_key": "value"}
    )
    assert accepted is False
    assert reason == "low_confidence_score"


def test_non_int_confidence_score_treated_as_zero():
    """Garbage confidence_score values default to 0 and trip the score gate."""
    accepted, reason = is_acceptable_lua(
        _WRAPPED_LUA, harness_report={"confidence_score": "garbage"}
    )
    assert accepted is False
    assert reason == "low_confidence_score"


def test_custom_min_length_and_min_confidence_respected():
    short_but_valid = "function processEvent(e) return {class_uid=4001} end"
    accepted, _ = is_acceptable_lua(
        short_but_valid,
        harness_report={"confidence_score": 60},
        min_length=20,
        min_confidence=60,
    )
    assert accepted is True
