"""Helpers for exporting parser Lua scripts from conversion output."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional

from .ai_siem_pipeline_converter import normalize_name
from .lua_deploy_wrapper import ensure_wrapped, wrap_for_observo  # noqa: F401 (wrap_for_observo imported for gate-test discovery)

GENERIC_EXTRACTION_LUA = """-- Generic parser extraction + serialization fallback
-- Generated by Purple Pipeline Parser Eater

local function trim(s)
    return (s:gsub("^%s+", ""):gsub("%s+$", ""))
end

local function parse_kv_pairs(msg)
    local out = {}
    if type(msg) ~= "string" then
        return out
    end

    for k, v in msg:gmatch("([%w%._-]+)=([^%s]+)") do
        out[k] = v
    end
    return out
end

local function parse_syslog_prefix(msg)
    if type(msg) ~= "string" then
        return nil
    end
    local month, day, time, host, body = msg:match("^(%a+)%s+(%d+)%s+(%d+:%d+:%d+)%s+([%w%._-]+)%s+(.*)$")
    if not month then
        return nil
    end
    return {
        month = month,
        day = tonumber(day),
        time = time,
        hostname = host,
        body = body,
    }
end

function processEvent(event)
    if event == nil then return nil end

    local src = event.log or event
    local out = {}

    if type(src) == "table" then
        for k, v in pairs(src) do
            out[k] = v
        end
        if src.message == nil and src.msg ~= nil then
            out.message = src.msg
        end
    elseif type(src) == "string" then
        out.message = src
    else
        out.message = tostring(src)
    end

    local msg = out.message
    local sys = parse_syslog_prefix(msg)
    if sys then
        out.syslog = sys
        out.message = sys.body or msg
    end

    local kv = parse_kv_pairs(out.message)
    if next(kv) ~= nil then
        out.extracted = kv
    end

    out.metadata = out.metadata or {}
    out.metadata.version = out.metadata.version or "1.0.0"
    out.metadata.product = out.metadata.product or { name = "Custom Parser", vendor_name = "Unknown" }

    -- Copy extracted fields back to event
    for k, v in pairs(out) do
        event[k] = v
    end

    return event
end
"""


def _find_serializer_script(processing_profile: Optional[Dict[str, Any]]) -> Optional[str]:
    if not isinstance(processing_profile, dict):
        return None
    components = processing_profile.get("serialization_components", [])
    if not isinstance(components, list):
        return None

    for component in components:
        if not isinstance(component, dict):
            continue
        config = component.get("config", {})
        if not isinstance(config, dict):
            continue
        groups = config.get("config_groups", [])
        if not isinstance(groups, list):
            continue
        for group in groups:
            if isinstance(group, dict):
                script = group.get("script")
                if isinstance(script, str) and script.strip():
                    return script
    return None


def build_lua_content(entry: Dict[str, Any]) -> Dict[str, str]:
    """Build standalone Lua content for a converted parser entry."""
    parser_name = entry.get("parser_name", "unknown")
    processing_profile = entry.get("processing_profile")
    script = _find_serializer_script(processing_profile)

    if script:
        source_kind = "template_serializer_script"
        body = script
    else:
        source_kind = "generic_fallback"
        body = GENERIC_EXTRACTION_LUA

    header = (
        f"-- parser: {parser_name}\n"
        f"-- ingestion_mode: {entry.get('ingestion_mode', 'unknown')}\n"
        f"-- processing_template_used: {entry.get('processing_template_used')}\n"
        f"-- generated_source: {source_kind}\n\n"
    )

    # Phase 2.F: route body through ensure_wrapped so deploy emits always
    # carry the outer ``process(event, emit)`` contract and the inlined OCSF
    # helpers. ``ensure_wrapped`` is idempotent — if ``body`` came from a
    # generator that already wrapped (detected via sentinel marker) it is
    # returned unchanged; otherwise it gets the full wrap treatment.
    wrapped_body = ensure_wrapped(body)

    return {
        "source_kind": source_kind,
        "content": header + wrapped_body + "\n",
    }


def export_lua_files(converted_entries: List[Dict[str, Any]], output_dir: Path) -> Dict[str, Any]:
    """Export standalone Lua files for converted parser entries."""
    output_dir.mkdir(parents=True, exist_ok=True)
    exported = []
    template_backed = 0
    fallback_backed = 0

    for entry in converted_entries:
        parser_name = entry.get("parser_name", "unknown")
        parser_slug = normalize_name(parser_name) or "unknown"
        lua_path = output_dir / f"{parser_slug}.lua"

        lua_data = build_lua_content(entry)
        source_kind = lua_data["source_kind"]
        if source_kind == "template_serializer_script":
            template_backed += 1
        else:
            fallback_backed += 1

        lua_path.write_text(lua_data["content"], encoding="utf-8")

        exported.append(
            {
                "parser_name": parser_name,
                "lua_file": str(lua_path),
                "generated_source": source_kind,
                "processing_template_used": entry.get("processing_template_used"),
            }
        )

    manifest = {
        "summary": {
            "total_exported": len(exported),
            "template_backed_total": template_backed,
            "fallback_total": fallback_backed,
        },
        "files": exported,
    }
    (output_dir / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return manifest
