-- parser: barracuda_firewall_logs_latest
-- ingestion_mode: syslog
-- processing_template_used: None
-- generated_source: generic_fallback

-- Generic parser extraction + serialization fallback
-- Generated by Purple Pipeline Parser Eater

local function trim(s)
    return (s:gsub("^%s+", ""):gsub("%s+$", ""))
end

local function parse_kv_pairs(msg)
    local out = {}
    if type(msg) ~= "string" then
        return out
    end

    for k, v in msg:gmatch("([%w%._-]+)=([^%s]+)") do
        out[k] = v
    end
    return out
end

local function parse_syslog_prefix(msg)
    if type(msg) ~= "string" then
        return nil
    end
    local month, day, time, host, body = msg:match("^(%a+)%s+(%d+)%s+(%d+:%d+:%d+)%s+([%w%._-]+)%s+(.*)$")
    if not month then
        return nil
    end
    return {
        month = month,
        day = tonumber(day),
        time = time,
        hostname = host,
        body = body,
    }
end

function process(event, emit)
    local src = event["log"]
    local out = {}

    if type(src) == "table" then
        for k, v in pairs(src) do
            out[k] = v
        end
        if src.message == nil and src.msg ~= nil then
            out.message = src.msg
        end
    elseif type(src) == "string" then
        out.message = src
    else
        out.message = tostring(src)
    end

    local msg = out.message
    local sys = parse_syslog_prefix(msg)
    if sys then
        out.syslog = sys
        out.message = sys.body or msg
    end

    local kv = parse_kv_pairs(out.message)
    if next(kv) ~= nil then
        out.extracted = kv
    end

    out.metadata = out.metadata or {}
    out.metadata.version = out.metadata.version or "1.0.0"
    out.metadata.product = out.metadata.product or { name = "Custom Parser", vendor_name = "Unknown" }

    event["log"] = out
    emit(event)
end

